import { renderApiDocs } from './api-docs.mjs';
const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const kb = n => `${(n / 1000).toFixed(1)} kB`;
const names = { 'notre-dame':'Notre-Dame de Paris', 'pantheon':'Panthéon' };
const title = a => names[a.id] || a.name;
const page = (name, body) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="An open collection of lightweight architectural landmarks. Explore models, download editable sources and contribute."><title>${esc(name)} · Open Landmarks</title><link rel="icon" type="image/svg+xml" href="/site/brand.svg"><link rel="stylesheet" href="/site/style.css"><script type="module" src="/site/client.js"></script></head><body><header><a class="brand" href="/" aria-label="Open Landmarks home"><img class="brand-mark" src="/site/brand.svg" width="36" height="36" alt=""><span class="brand-name">Open Landmarks</span></a><nav aria-label="Main navigation"><a href="/#collection">Collection</a><a href="/docs/">Documentation</a><a href="/contribute/">Contribute<svg class="nav-arrow" width="15" height="15" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M4 12 12 4M4.5 4H12v7.5" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg></a></nav></header>${body}<footer><a class="brand" href="/">Open Landmarks</a><p>Made for maps. Open to everyone.</p><div><a href="/licenses/">Licensing</a><a href="/api/v1/collections.json">Data API</a><a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a></div></footer></body></html>`;
const card = a => `<a class="card" href="/landmarks/${a.id}/" data-search="${esc([a.name,a.id,...a.aliases].join(' '))}"><div class="card-image"><img src="${a.preview.url}" alt="3D model of ${esc(title(a))}" width="640" height="533" loading="lazy"><span class="tag">${a.approved ? 'Reviewed' : 'Draft'}</span></div><div class="card-info"><div><h3>${esc(title(a))}</h3><p>Paris, France</p></div><span aria-hidden="true">↗</span></div><div class="card-meta"><span>${a.lods.detail.triangles.toLocaleString('en-US')} triangles</span><span>${kb(a.lods.detail.gzip.bytes)} gzip</span></div></a>`;

export async function renderSite(assets, catalogue, emit) {
  const sorted = [...assets].sort((a,b) => ['notre-dame','eiffel-tower','arc-de-triomphe','sainte-chapelle','pantheon'].indexOf(a.id) - ['notre-dame','eiffel-tower','arc-de-triomphe','sainte-chapelle','pantheon'].indexOf(b.id));
  const hero = sorted[0];
  await emit('/index.html', page('Architecture, at map scale', `<main><section class="hero"><div class="hero-copy"><h1>An open collection of 3D models made to work on maps.</h1><p class="intro">Light and instantly recognizable, the landmarks in this dataset are built to be consistent and load fast on maps.</p><div class="actions"><a class="button" href="#collection">Explore the collection <span>↓</span></a><a class="text-link" href="/docs/">Read the docs ↗</a><a class="text-link" href="https://benmaps.fr" target="_blank" rel="noopener noreferrer">Demo ↗</a></div></div><a class="hero-art" href="/landmarks/${hero.id}/"><img src="${hero.preview.url}" alt="${esc(title(hero))}, simplified in pale stone and muted roofs" width="640" height="533" fetchpriority="high"><div class="art-caption"><span>01 / Paris</span><strong>${esc(title(hero))} <span>↗</span></strong></div></a></section><section class="collection" id="collection"><div class="section-heading"><div><p class="eyebrow">The first collection</p><h2>A little more Paris.</h2></div></div><div class="collection-controls"><span class="city-pill">Paris <span>${assets.length}</span></span><label class="search"><span aria-hidden="true">⌕</span><input type="search" id="search" placeholder="Find a landmark…" aria-label="Search landmarks"></label></div><div class="grid">${sorted.map(card).join('')}</div><p id="search-status" role="status" aria-live="polite"></p></section><section class="contribute-banner"><div><p class="eyebrow">A growing atlas</p><h2>Your city belongs here, too.</h2><p>Model by hand, write a script, or work with AI. What matters is the result—and a clear account of where it came from.</p></div><a class="button secondary" href="/contribute/">Contribute a landmark ↗</a></section></main>`));

  for (const a of assets) {
    const data = JSON.stringify({ url: a.lods.detail.url, gzip: a.lods.detail.gzip.url, name: a.name }).replace(/</g, '\\u003c');
    const download = (label, item) => `<a class="download" href="${item.url}" download><span>${label}</span><span>${kb(item.bytes)} ↓</span></a>`;
    await emit(`/landmarks/${a.id}/index.html`, page(title(a), `<main class="detail"><a class="back" href="/#collection">← All landmarks</a><div class="detail-heading"><div><p class="eyebrow">Paris, France · ${a.approved ? 'Reviewed' : 'Draft model'}</p><h1>${esc(title(a))}</h1></div><a href="${esc(a.osm.url)}" class="text-link">View footprint on OSM ↗</a></div><div class="detail-layout"><section class="viewer-section"><div class="viewer" id="viewer"><img src="${a.preview.url}" alt="Preview of ${esc(title(a))}" width="640" height="533"><button class="button preview-button" id="load-preview">Explore in 3D ↗</button></div><div class="viewer-controls"><p id="preview-status" role="status">Interactive preview loads only when you ask.</p><label hidden id="light-control">Light <select id="light"><option value="day">Day</option><option value="night">Night</option></select></label></div><script id="preview-data" type="application/json">${data}</script></section><aside><h2>Take it with you.</h2><p>Texture-free geometry, two levels of detail, and editable source.</p>${download('GLB · detail',a.lods.detail)}${download('GLB · low detail',a.lods.low)}${download('GLB · detail, gzip file',a.lods.detail.gzip)}${download('Blender source · gzip file',a.source)}${download('OSM spatial source · JSON',a.spatialSource)}<p class="download-note">Gzip files need decompression before opening. Downloads carry the component licenses described below.</p><dl class="specs"><div><dt>Detail triangles</dt><dd>${a.lods.detail.triangles.toLocaleString('en-US')}</dd></div><div><dt>Height</dt><dd>${a.boundsBlenderM[1][2].toFixed(1)} m</dd></div><div><dt>Textures</dt><dd>None</dd></div><div><dt>Coordinates</dt><dd>${a.anchor.map(v=>v.toFixed(5)).join(', ')}</dd></div></dl><a class="text-link" href="${a.metadata}">Full metadata & attribution ↗</a></aside></div><section class="detail-notes"><div><h2>Open, with provenance.</h2><p>${esc(a.licenseScope)}</p><p>${esc(a.attribution)}. <a href="/licenses/">Read the licensing guide.</a></p><p>${esc(a.assistance)}</p><h3>Visual references</h3><ul>${a.references.map(r=>`<li><a href="${esc(r.sourcePage)}">${esc(r.title.replace(/^File:/,''))}</a> — ${esc(r.author)}, <a href="${esc(r.licenseUrl)}">${esc(r.license)}</a></li>`).join('')}</ul></div><div><h2>Review status</h2><p>${a.approved ? 'Approved for this exact revision.' : 'This model is a prototype. Structural validation passes; footprint, appearance, map integration and rights still need approval.'}</p><p><a href="${a.validation}">Read structural validation ↗</a></p><p class="muted">Revision <code>${a.revision.slice(0,16)}</code></p></div></section></main>`));
  }
  const docShell = (label, headline, body) => page(label, `<main class="docs"><aside><p class="eyebrow">Documentation</p><a href="/docs/">API reference</a><a href="/contribute/">Contributing models</a><a href="/licenses/">Licensing & attribution</a></aside><article><p class="eyebrow">Open Landmarks / ${label}</p><h1>${headline}</h1>${body}</article></main>`);
  await emit('/docs/index.html', docShell('Documentation', 'API reference', renderApiDocs(assets, catalogue)));
  await emit('/contribute/index.html', docShell('Contribute', 'Bring a place<br>you know.', `<p class="lead">A good contribution is recognizable, correctly placed and inexpensive to render. How you make it is up to you.</p><h2>Choose your tools</h2><p>Model in Blender by hand, use procedural scripts, or use AI assistance. You do not need the original author's generator, an AI subscription or access to a private service. Submit an editable Blender source and two GLBs. Disclose AI assistance and other third-party inputs in the metadata.</p><h2>Keep the architecture, lose the weight</h2><p>Prioritize the silhouette, major roof forms, openings and structural rhythm. Aim for fewer than 8,000 triangles, six materials and six draw calls; each GLB must be at most 250 kB before compression. V1 uses opaque, texture-free materials, static triangles and applied transforms. Include a genuinely simpler LOD when it preserves the silhouette.</p><h2>Prepare a submission</h2><ol><li>Copy the <a href="/contribution-template.json" download>metadata template</a> into <code>collection/your-landmark/asset.json</code>.</li><li>Add <code>detail.glb</code>, <code>low.glb</code>, <code>source.blend.gz</code>, <code>spatial-source.json</code> and a small <code>preview.webp</code>.</li><li>Record the OSM IDs, versions, geometry and timestamp; list reference authors, source pages and licenses. Do not copy imagery from commercial maps.</li><li>Run <code>npm ci</code> then <code>npm run validate</code>. Fill in exact byte counts and SHA-256 hashes. Existing submissions are complete examples.</li><li>Submit a pull request to the collection repository once it is published. Keep the review state pending; maintainers approve the exact content revision.</li></ol><p>The repository is being prepared for publication. Downloads and the submission format are available here now.</p><h2>What gets reviewed</h2><p>Automated checks cover glTF validity, hashes, size budgets, transforms, normals, triangles, materials and declared 3D bounds. A maintainer also checks footprint fit, architectural identity, multiple camera angles, lightness, night lighting, basemap overlap and licensing. Passing the validator alone does not approve a model.</p><h2>What you agree to share</h2><p>Your original artistic contribution is offered under CC BY 4.0; OSM-derived spatial data remains under ODbL 1.0. Provide editable source and provenance alongside the exports. You can keep your production tools private, provided you can grant the submitted rights and meet the source-data obligations. <a href="/licenses/">Read the full component policy.</a></p>`));
  await emit('/licenses/index.html', docShell('Licensing', 'Open, with<br>clear origins.', `<p class="lead">Different parts of the collection have different licenses. These obligations apply to their respective components; they are not alternative licenses to choose between.</p><h2>Models</h2><p>Original artistic contributions are offered under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>, to the extent contributors hold those rights. Credit the named authors and identify your changes. This does not replace obligations for embedded spatial data or other third-party content.</p><h2>Spatial data and index</h2><p>OSM-derived footprints, building parts, placement data and the catalogue are distributed under <a href="https://opendatacommons.org/licenses/odbl/1-0/">ODbL 1.0</a>. Retain <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a> attribution and comply with applicable database sharing obligations. Each model and release includes machine-readable source data.</p><h2>References</h2><p>Reference photographs retain their original licenses. We list their source pages, authors and terms in model metadata. Photographs are not redistributed in this package or used as textures. Reference licensing and architectural rights are part of the review; a pending model is not a certification of those rights.</p><h2>Code</h2><p>The original site, index builder and contribution tools use the <a href="/licenses/MIT.txt">MIT license</a>. The optional browser preview uses <a href="/licenses/THREE.txt">Three.js under MIT</a>. <a href="/licenses/COMPONENTS.md">Download the component notice.</a></p><h2>Draft status</h2><p>The Paris prototypes are available for inspection and contribution. Their rights and visual reviews are pending. Production consumers should use the approved catalogue endpoint, which excludes pending submissions.</p>`));
  await emit('/404.html', page('Page not found', '<main class="docs"><article><p class="eyebrow">404</p><h1>A place yet<br>to be found.</h1><p>This page does not exist.</p><a class="button" href="/">Back to the collection</a></article></main>'));
  const { readFile } = await import('node:fs/promises');
  await emit('/contribution-template.json', await readFile(new URL('../templates/asset.json', import.meta.url)));
}
